server:
  port: 9090

spring:
  redis:
    host: localhost
    port : 6379       # Redis服务器连接端口
    password :        # Redis服务器连接密码（默认为空）
    pool:
      max-active : -1  # 连接池最大连接数（使用负值表示没有限制）
      max-idle : 8    # 连接池中的最大空闲连接
      max-wait : -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle : 0    # 连接池中的最小空闲连接


#日志配合·标准
logging:
  config: classpath:logback-boot.xml

